### ISSUE TITLE
Update package to use guzzlehttp/guzzle?

### ISSUE THREAD

**Issue by nick-f** [moltin/currency#11]
When running `composer update` an error message shows saying:

> Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

`composer why guzzle/guzzle` says currency is the package that requires it.

Is there reasonably any chance that this package would be updated or would it be quicker to implement the changes and overwrite?

(Although, based on #10, I'm not exactly going to be surprised if I end up having to try and implement the changes)

Thanks!

**Comment by erayaydin** [comment]
:+1:

**Comment by erayaydin** [comment]
Last commit on 2014 :disappointed:

**Comment by zot24** [comment]
Hi guys @erayaydin @nick-f! I have just sort out that issue (merge a PR that update that package) and introduce some tags to the repo so easier to use https://github.com/moltin/currency/releases/tag/1.1.0 hops that helps.
