### ISSUE TITLE
Class 'Guzzle\Http\Client' not found"

### ISSUE THREAD

**Issue by hoannv** [moltin/currency#15]
Hi there,
I just update moltin/currency to latest version and have an issue occurred.

"moltin/currency": "1.1.0",
"guzzlehttp/guzzle": "6.*",

Class 'Guzzle\Http\Client' not found" in 
https://github.com/moltin/currency/blob/5c6892e0daa02d09453e1cd16297ae2f1397b79e/src/Moltin/Currency/Exchange/OpenExchangeRates.php#L24
It seems namespace of this class 'Guzzle\Http\Client' is not updated.

**Comment by notrab** [comment]
Hey, this project is unmaintained. I’d recommend you seek an alternate package 🙂

**Comment by hoannv** [comment]
@notrab If I fix and make pull request, can you merge it?

**Comment by notrab** [comment]
@hoannv I've gone ahead and added you as a maintainer. Feel free to PR & merge 😅

**Comment by hoannv** [comment]
@notrab I can't enable two-factor authentication because github doesn't support sms for Vietnam number

**Comment by notrab** [comment]
@hoannv you should be able to follow details [here](https://help.github.com/en/articles/configuring-two-factor-authentication) for countries that are not supported.

**Comment by hoannv** [comment]
@notrab Can you able to disable this option temporarily? After I push new commit, you ca turn it back.
