### ISSUE TITLE
Cache Support

### ISSUE THREAD

**Issue by alekseyp** [moltin/currency#9]
Hi there,

I'm just curious if anyone is interested in caching functionality?
Let's say get an exchange rates and cache them for a day or so, i'm pretty sure everyone has an instance of the memcache running.

Or it's better just to do it on my application side?

Let me know what you think.

**Comment by outrunthewolf** [comment]
Hi @alekseyp it would be possible to write caching into this package, but it would have to be done in such a way that people could swap it our for their particular product (memched, redis, file etc..). It may be that it detracts from the simplicity of itself.

    Or it's better just to do it on my application side?

That's essentially what we do. By extending the package in our own system we can take the basic blocks it gives us and handle caching in a way specific to our application.

That said, if you think you've got a great idea, we're always open to p/r's and improvements.

**Comment by alekseyp** [comment]
@outrunthewolf, yeah, that what i thought and did so far.

I don't have anything in mind right now, so i think it' safe to close the issue.
Or should I keep it open to see if anyone else is interested?
